INFO     HTTP_CLIENT:event_hooks.py:24 Отправляем запрос: POST на http://localhost:8001/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:28 Получаем ответ: 422 Unprocessable Entity от http://localhost:8001/api/v1/users
INFO     BASE_ASSERTIONS:base.py:24 Проверяем, что статус код ответа сервера соответствует 422
INFO     USERS_ASSERTIONS:users.py:161 Проверям ответ сервера после запроса на создание или обновление пользователя со значением, превышающим максимальную длину поля.
INFO     ERRORS_ASSSERTIONS:errors.py:172 Проверям ошибку валидации для значения, превышающего максимальную длину поля lastName
INFO     ERRORS_ASSSERTIONS:errors.py:54 Проверяем ответ сервера с ожидаемой валидационной ошибкой
INFO     BASE_ASSERTIONS:base.py:82 Проверяем, что длина details соответствует ожидаемой [ValidationErrorSchema(type='string_too_long', input='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', context={'max_length': 50}, message='String should have at most 50 characters', location=['body', 'lastName'])]
INFO     ERRORS_ASSSERTIONS:errors.py:31 Проверяем данные ожидаемой валидационной ошибки
INFO     BASE_ASSERTIONS:base.py:45 Проверяем, что значение type соответствует ожидаемому string_too_long
INFO     BASE_ASSERTIONS:base.py:45 Проверяем, что значение message соответствует ожидаемому String should have at most 50 characters
INFO     BASE_ASSERTIONS:base.py:45 Проверяем, что значение location соответствует ожидаемому ['body', 'lastName']
INFO     BASE_ASSERTIONS:base.py:45 Проверяем, что значение input соответствует ожидаемому aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
INFO     BASE_ASSERTIONS:base.py:45 Проверяем, что значение context соответствует ожидаемому {'max_length': 50}
INFO     SCHEMA_ASSERTIONS:schema.py:26 Проверяем, соответствует ли ответ сервера JSON-схеме